[cerebrium.deployment]
name = "resnet18-classifier"
python_version = "3.11"
include = ["./*"]
exclude = [".*", "__pycache__", "*.pyc", ".git", "test.py", "convert_to_onnx.py", "pytorch_model.py", "pytorch_model_weights.pth"]

[cerebrium.hardware]
cpu = 2
memory = 4.0
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.runtime.custom]
port = 8000
healthcheck_endpoint = "/health"
dockerfile_path = "./Dockerfile"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 10
cooldown = 300
replica_concurrency = 10 